### ISSUE TITLE
no _site file in template pull 

### ISSUE THREAD

**Issue by lilydemet** [ubc-library-rc/intro-mapbox#1]
wont publish to site (only locally)

**Comment by lilydemet** [comment]
oh I realize I have to git add _site/ for the markdown files to be published in html according to the jekyll site template style (clarification needed)

**Comment by lilydemet** [comment]
resolved it!

**Comment by lilydemet** [comment]
_site/ folder now existant but https://ubc-library-rc.github.io/intro-mapbox/ doesnt show workshop UI in progress? @ect123

**Comment by ect123** [comment]
Looks to me like you just need to publish the GitHub repo with Pages. This will enable the content in `_site` to be served as a static site. That would be step 3 here: https://ubc-library-rc.github.io/rc-workshop-template/.

**Comment by lilydemet** [comment]
Went to repo Settings in GitHub --> Pages --> set source branch to main
