### ISSUE TITLE
Run failed: pages build and deployment 

### ISSUE THREAD

**Issue by lilydemet** [ubc-library-rc/intro-mapbox#14]
@ect123 It seems my latest push failed and I'm not sure why. The changes made to the tracked files are visible though. The "Clustering" sub-page of Build a Webmap should be all filled out and Style and Prepare Data were removed. 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/73118858/212438894-7c5cce7c-3b64-4db2-b7ea-8d38d5880c4c.png">

**Comment by ect123** [comment]
Looks like it might be caused by a few lines in your config file. Is this something that's being used?
```
  features: 
    - content.code.copy
    - content.code.annotate
```
If not, I would remove them and push the changes. Looking at the build error log that might fix the issue.

**Comment by lilydemet** [comment]
oh!! thank you. Yeah that can be scrapped- left over from trying out ways
to highlight in code locks.
